services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    links:
      - php
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '9000:9000'
    user: dev

